CREATE TABLE IF NOT EXISTS queue_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token_id UUID NOT NULL REFERENCES tokens(id) ON DELETE CASCADE,
    event_type VARCHAR(100) NOT NULL CHECK (event_type IN ('TOKEN_CREATED', 'TOKEN_APPROVED', 'TOKEN_REJECTED', 'TOKEN_CALLED', 'TOKEN_SERVING', 'TOKEN_SKIPPED', 'TOKEN_RECALLED', 'TOKEN_COMPLETED', 'TOKEN_CANCELLED')),
    old_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    performed_by UUID REFERENCES users(id) ON DELETE SET NULL,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
